#!/bin/bash

set -e 


rm -rf dist
python3 setup.py sdist bdist_wheel
# python2 setup.py sdist bdist_wheel


gnome-keyring-daemon
source token


python3 -m twine check dist/*
python3 -m twine upload dist/*

