#!/bin/bash


if [ "$USER" != "root" ]; then
    echo "Need root to do proper zfs testing"
    exit 1
fi

#reactivate python environment, if any (usefull in Travis)
[ "$VIRTUAL_ENV" ] && source $VIRTUAL_ENV/bin/activate 

# test needs ssh access to localhost for testing
if ! [ -e /root/.ssh/id_rsa ]; then
    ssh-keygen -t rsa -f /root/.ssh/id_rsa -P '' || exit 1
    cat /root/.ssh/id_rsa.pub  >> /root/.ssh/authorized_keys || exit 1
    ssh -oStrictHostKeyChecking=no localhost true || exit 1
fi

coverage run --source bin.zfs_autobackup -m unittest -v $@ 
EXIT=$?

echo 
coverage report

#this does automatic travis CI/https://coveralls.io/ intergration:
if which coveralls > /dev/null; then
        echo "Submitting to coveralls.io:"
        coveralls 
fi

exit $EXIT
