#!/bin/sh

#NOTE: This script will started inside the test docker container

set -e

if ! [ -e /.dockerenv ]; then
  echo "only run this script inside a docker container!"
  exit 1
fi

if ! [ -e /dev/ram0 ]; then
    echo "Please load this module outside container:" >&2
    echo "sudo modprobe brd rd_size=512000" >&2
    exit 1

fi

#start sshd and other stuff
ssh-keygen -A
/usr/sbin/sshd
udevd -d


#config ssh
if ! [ -e /root/.ssh/id_rsa ]; then
    ssh-keygen -t rsa -f /root/.ssh/id_rsa -P ''
fi

cat >> ~/.ssh/config <<EOF
Host *
    addkeystoagent yes
    controlpath ~/.ssh/control-master-%r@%h:%p
    controlmaster auto
    controlpersist 3600
EOF

cat /root/.ssh/id_rsa.pub  >> /root/.ssh/authorized_keys
ssh -oStrictHostKeyChecking=no localhost 'echo SSH OK' 

cd /app
python -m unittest discover /app/tests -vvvvf $@
